services:
  lcv.include_archived_listener:
    class: LCV\DoctrineODMSoftDeleteBundle\Annotation\IncludeArchivedListener
    arguments: ["@annotations.reader", "@doctrine_mongodb.odm.default_document_manager"]
    tags:
      - { name: kernel.event_listener, event: kernel.controller }

  lcv.archive_manager:
    class: LCV\DoctrineODMSoftDeleteBundle\Manager\ArchiveManager
    arguments: ["@doctrine_mongodb.odm.default_document_manager"]


  lcv.soft_delete_validator:
    class: LCV\DoctrineODMSoftDeleteBundle\Formulary\SoftDeleteValidator
    arguments: ["@lcv.archive_manager", "@translator.default"]

  lcv.archivable_validator:
    class: LCV\DoctrineODMSoftDeleteBundle\Formulary\ArchivableValidator
    arguments: ["@lcv.archive_manager", "@translator.default"]

  LCV\DoctrineODMSoftDeleteBundle\Formulary\SoftDeleteValidator: '@lcv.soft_delete_validator'
  LCV\DoctrineODMSoftDeleteBundle\Formulary\ArchivableValidator: '@lcv.archivable_validator'
  LCV\DoctrineODMSoftDeleteBundle\Manager\ArchiveManager: '@lcv.archive_manager'
