services:
  lcv.ignore_soft_delete_listener:
    class: LCV\DoctrineODMSoftDeleteBundle\Annotation\IgnoreSoftDeleteListener
    arguments: ["@annotations.reader", "@doctrine_mongodb.odm.default_document_manager"]
    tags:
      - { name: kernel.event_listener, event: kernel.controller }

  lcv.soft_delete_manager:
    class: LCV\DoctrineODMSoftDeleteBundle\Manager\SoftDeleteManager
    arguments: ["@doctrine_mongodb.odm.default_document_manager"]


  lcv.soft_delete_validator:
    class: LCV\DoctrineODMSoftDeleteBundle\Formulary\SoftDeleteValidator
    arguments: ["@lcv.soft_delete_manager", "@translator.default"]

  LCV\DoctrineODMSoftDeleteBundle\Formulary\SoftDeleteValidator: '@lcv.soft_delete_validator'